### ISSUE TITLE
农历结束时间在开始时间之前

### ISSUE THREAD

**Issue by zheng7fu2** [YangH9/ChinaHolidayCalender#1]
![image](https://github.com/YangH9/ChinaHolidayCalender/assets/5558872/94413759-6324-4141-aabc-eacb2db486fe)

**Comment by YangH9** [comment]
设备型号、系统版本多少，我这里没遇到过全天日程还会显示开始结束时间的，而且数据里面全天日程的开始结束时间只有年月日

**Comment by zheng7fu2** [comment]
Arch Linux 
Thunderbird 115.9.0

订阅农历也会出现 

![2024-03-26_11-19](https://github.com/YangH9/ChinaHolidayCalender/assets/5558872/83838204-0b0e-48be-8527-569d339c1778)

**Comment by zheng7fu2** [comment]
我在Thunderbird中新建了一个本地ics日历，将 农历 中的任意一天的事件复制到本地日历。
在编辑页面中 结束日期是在开始日期之前；
手动改成 结束日期与开始日期是同一天，其他未做修改。
![image](https://github.com/YangH9/ChinaHolidayCalender/assets/5558872/c6b971e2-6de7-414a-9404-3c1f48dc14e3)


导出ics文件，使用文本编辑器打开：

`BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VEVENT
CREATED:20240327T000001
LAST-MODIFIED:20240326T042239Z
DTSTAMP:20240326T042239Z
UID:20240327T000001_lunar_1548@YangH9
SUMMARY:『二月 十八 2024年』
STATUS:CONFIRMED
DTSTART;VALUE=DATE:20240327
DTEND;VALUE=DATE:20240328
LOCATION:甲辰 龙年 丁卯月 庚寅日
DESCRIPTION:2024年 二月 十八\n甲辰 龙年 丁卯月 庚寅日\n日
 期：2024年03月27日\n\n2020~2025年中华人民共和国农历、天干
 地支日历。更新时间：2024-03-24
TRANSP:TRANSPARENT
SEQUENCE:2
X-MOZ-GENERATION:1
END:VEVENT
END:VCALENDAR
`
看到  DTEND;VALUE=DATE:20240328  

猜测可能是 https://www.rfc-editor.org/rfc/rfc5545#section-3.8.2.2

`The value type    of this property MUST be the same as the "DTSTART" property, and   its value MUST be later in time than the value of the "DTSTART"    property.  `

**Comment by YangH9** [comment]
大概明白了，我改了一下，看一下时间对没
